# 3. Array Operations

* Arithmetic operations on NumPy arrays (addition, subtraction, multiplication, division).
Broadcasting (performing operations on arrays of different shapes).
Element-wise operations and functions (e.g., np.sqrt(), np.sin(), np.exp()).

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1,2,3,4,5])
print(arr1+arr2)


[ 2  4  6  8 10]


In [5]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1,2,3,4,5])
print(arr1-arr2)


[0 0 0 0 0]


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1,2,3,4,5])
print(arr1*arr2)


[ 1  4  9 16 25]


In [7]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1,2,3,4,5])
print(arr1/arr2)


[1. 1. 1. 1. 1.]


In [8]:
import numpy as np
a=np.array([1,4,5,6])
print(a)
print(a*5)#scaler

[1 4 5 6]
[ 5 20 25 30]


In [9]:
import numpy as np
arr1=np.array([1,4,5,6])
print(arr1)
print(arr1.shape)# shapeing
print(arr1.ndim)# which diam

[1 4 5 6]
(4,)
1


In [11]:
import numpy as np
arr1=np.array([[1,4,7]])
arr2=np.array([[1,4,5],[3,5,6]])
print(arr2.shape)
print(arr1+arr2)# mapping

(2, 3)
[[ 2  8 12]
 [ 4  9 13]]


In [14]:
import numpy as np

# Create an array
arr = np.array([1 , 2 , 3 , 4 , 5 ])

# Perform element-wise power and root functions
print("Square Root:", np.sqrt(arr))

Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]


In [15]:
import numpy as np

arr = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])

print("Sine:", np.sin(arr))

Sine: [ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Exponential:", np.exp(arr))

Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


# 4. Array Shapes and Reshaping

* Checking array dimensions with .shape and .ndim.
Changing array shape with .reshape(), .flatten(), .transpose().
Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().

In [18]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print("Array shape:", arr.shape)

Array shape: (2, 3)


In [19]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print("Number of dimensions:", arr.ndim)

Number of dimensions: 2


In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])

reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [22]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])  
print("Original shape:", arr.shape)  # Output: (2, 3)
flat_arr = arr.flatten()  
print("Flattened shape:", flat_arr.shape)  # Output: (6,)
print(flat_arr)  # Output: [1 2 3 4 5 6]

Original shape: (2, 3)
Flattened shape: (6,)
[1 2 3 4 5 6]


In [24]:
# importing python module named numpy
import numpy as np

# making a 3x3 array
gfg = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# before transpose
print(gfg, end ='\n\n')

# after transpose
print(gfg.transpose())

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [25]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c = np.concatenate((a, b), axis=0)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a,b))
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
import numpy as np
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
import numpy as np
arr = np.array([1,2,3,4,5])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5])]
