# 1. Introduction to NumPy


* What NumPy is and why it’s important for numerical computations in Python.
Installation of NumPy (pip install numpy).
Understanding its role in data science, machine learning, and scientific computing.


In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# 2. Arrays in NumPy


* Creating arrays using np.array(), np.zeros(), np.ones(), np.arange(), and np.linspace().
Array indexing and slicing.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr = np.zeros(5)
print(arr)
print(type(arr))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
arr = np.ones(5)
print(arr)
print(type(arr))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


* 0D array

In [12]:
import numpy as np

arr = np.array(45)

print(arr)

45


* 1D array

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


* 2D array

In [14]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


* 3D array

In [15]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# 3. Array Operations

In [20]:
import numpy as np 

#create an array 
arr= np.arange(10,0,-1)
print(arr)

[10  9  8  7  6  5  4  3  2  1]


In [21]:
import numpy as np

# Generate 10 numbers between 0 and 1
array = np.linspace(0, 1, num=10)
print(array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [23]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [24]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [25]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]
